# Generated by Django 5.1.6 on 2025-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YelpEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("rating", models.FloatField()),
                ("price", models.CharField(blank=True, max_length=10)),
                ("categories", models.JSONField()),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="rain_chance",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
