# Generated by Django 5.1.6 on 2025-04-11 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_weatherdata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherdata",
            options={"managed": False},
        ),
    ]
