# Generated by Django 5.1.6 on 2025-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_yelpevent_alter_weatherdata_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="forecast",
            field=models.JSONField(default=list),
        ),
    ]
