# Generated by Django 5.1.6 on 2025-04-15 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_weatherdata_forecast"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="forecast",
        ),
    ]
