# Generated by Django 5.1.6 on 2025-04-11 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_weatherdata_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="weatherdata",
            table="weather_data",
        ),
    ]
