# Generated by Django 5.1.6 on 2025-04-17 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_weatherdata_forecast"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="description",
            field=models.CharField(default="No description available", max_length=255),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="temperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="yelpevent",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="yelpevent",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="yelpevent",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="yelpevent",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="yelpevent",
            name="price",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="yelpevent",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "activities",
                    models.ManyToManyField(related_name="trips", to="api.yelpevent"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_users",
                    models.ManyToManyField(
                        related_name="invited_trips", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
