# Generated by Django 5.1.6 on 2025-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_userprofile_updated_at_alter_userprofile_followers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("forecast_date", models.DateField()),
                ("temperature_min", models.FloatField()),
                ("temperature_max", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                ("rain_chance", models.FloatField(default=0.0)),
                ("weather_conditions", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
