# Generated by Django 5.1.6 on 2025-04-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_weatherforecast"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="location",
            field=models.CharField(
                default="Unknown",
                help_text="City or destination name for the trip",
                max_length=255,
            ),
        ),
    ]
