# Generated by Django 5.2 on 2025-04-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trip_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.DeleteModel(
            name='WeatherForecast',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='activities',
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary',
            field=models.JSONField(blank=True, help_text='Generated itinerary schedule', null=True),
        ),
        migrations.DeleteModel(
            name='YelpEvent',
        ),
    ]
