# Generated by Django 5.1.6 on 2025-04-27 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_delete_weatherdata_delete_weatherforecast_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("price", models.CharField(blank=True, max_length=10, null=True)),
                ("categories", models.JSONField(default=list)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("YELP", "Yelp API"),
                            ("TICKETMASTER", "Ticketmaster API"),
                            ("MANUAL", "Manually Added"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterField(
            model_name="trip",
            name="invited_users",
            field=models.ManyToManyField(
                blank=True, related_name="invited_trips", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="itinerary",
            field=models.JSONField(
                blank=True, help_text="Generated itinerary schedule (legacy)", null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="activities",
            field=models.ManyToManyField(
                blank=True, related_name="trips", to="api.activity"
            ),
        ),
        migrations.CreateModel(
            name="DayActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("lunch", "Lunch"),
                            ("afternoon", "Afternoon"),
                            ("dinner", "Dinner"),
                            ("evening", "Evening"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_activities",
                        to="api.activity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Day Activities",
                "ordering": ["time_slot", "order"],
            },
        ),
        migrations.CreateModel(
            name="TripDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "activities",
                    models.ManyToManyField(
                        related_name="trip_day", to="api.dayactivity"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trip Days",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="days",
            field=models.ManyToManyField(
                blank=True, related_name="trip", to="api.tripday"
            ),
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("temperature", models.FloatField()),
                (
                    "description",
                    models.CharField(
                        default="No description available", max_length=255
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("rain_chance", models.FloatField(default=0.0)),
                ("weather_conditions", models.JSONField(default=dict)),
            ],
            options={
                "unique_together": {("location", "date")},
            },
        ),
        migrations.AddField(
            model_name="tripday",
            name="weather",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trip_days",
                to="api.weather",
            ),
        ),
    ]
