# Generated by Django 5.2 on 2025-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activity_alter_trip_invited_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
